# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e1ed5bf4ca25e06e786a0710e6fd6db87655e1b584803b7356210968bf58b34091acc32d895c44bf29475c24b0ea90b1b6d4126918904081a20f7741dc6b212

test:
  secret_key_base: 86ee1366c323084978d6f78569565b3a917ad834c2635a33f801cd19c9329821d3cb06fedd072584bb0230dd2d4bbde2043c736a97a9af30ff33958631985510

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
